extends SceneTree
var game
var failures := 0
func _initialize() -> void: call_deferred("run")
func check(ok: bool,label: String) -> void:
	if ok: print("PASS: "+label)
	else: failures+=1; push_error("FAIL: "+label)
func frames(count: int) -> void:
	for i in range(count): await physics_frame
func arrange() -> void:
	game.start_match(false,false)
	game.set_physics_process(false)
	for i in range(22):
		game.players[i].position=Vector3(-27+i*2.3,0,10 if i<11 else -15)
	game.players[9].position=Vector3(0,0,-20)
	game.players[10].position=Vector3(0,0,-40)
	game.players[11].position=Vector3(0,0,-49)
	game.players[12].position=Vector3(8,0,-30)
	game.ball.place(Vector3(0,0.23,-20))
	await frames(3)
func run() -> void:
	game=load("res://main.tscn").instantiate()
	root.add_child(game)
	await frames(3)
	await arrange()
	game.strike(9,Vector3(0,0,-15))
	check(10 in game.rules.candidates and game.state=="playing","Offside is recorded at the pass without stopping an uninvolved player")
	game.players[10].position.z=-22
	check(not game.rules.before_touch(10) and game.restart_type=="ENDİREKT VURUŞ" and game.restart_team==1,"An offside receiver returning behind defenders is still penalized on involvement")
	await arrange()
	game.players[10].position.z=-30
	game.strike(9,Vector3(0,0,-15))
	check(not 10 in game.rules.candidates,"A receiver level with the second-last defender is onside")
	await arrange()
	game.players[10].position.z=3
	game.strike(9,Vector3(0,0,15))
	check(not 10 in game.rules.candidates,"A receiver in their own half cannot be offside")
	await arrange()
	game.ball.place(Vector3(0,0.23,-43))
	await frames(3)
	game.strike(9,Vector3(0,0,10))
	check(not 10 in game.rules.candidates,"A receiver behind the ball is onside even beyond the defenders")
	for kind in ["TAÇ","KORNER","KALE VURUŞU"]:
		await arrange()
		game.rules.restart_taken(kind,0,9)
		game.strike(9,Vector3(0,2,-15))
		check(game.rules.candidates.is_empty(),"Direct reception from "+kind+" is exempt from offside")
	await arrange()
	game.rules.restart_taken("SERBEST VURUŞ",0,9)
	game.strike(9,Vector3(0,2,-15))
	check(10 in game.rules.candidates,"A free kick still creates normal offside positions")
	await arrange()
	game.strike(9,Vector3(0,2,-15))
	game.rules.before_touch(12,false)
	check(10 in game.rules.candidates,"An accidental defender deflection does not erase offside")
	game.rules.before_touch(12,true)
	check(game.rules.candidates.is_empty(),"Deliberate opponent control starts a new phase")
	await arrange()
	game.strike(9,Vector3(0,2,-15))
	game.strike(11,Vector3(3,2,10),0,true)
	check(10 in game.rules.candidates,"A keeper save preserves offside on the rebound")
	await arrange()
	game.rules.restart_taken("SERBEST VURUŞ",0,9)
	game.strike(9,Vector3(4,1,-12))
	game.rules.touch_age=1
	check(not game.rules.before_touch(9) and game.restart_type=="ENDİREKT VURUŞ","Restart taker cannot touch twice before another player")
	await arrange()
	game.players[10].position.z=-23
	game.rules.restart_taken("SERBEST VURUŞ",0,9)
	game.strike(9,Vector3(4,1,-12))
	game.rules.before_touch(10)
	game.rules.touch_age=1
	check(game.rules.before_touch(9),"Another player's touch releases the second-touch restriction")
	for kind in ["TAÇ","ENDİREKT VURUŞ"]:
		await arrange()
		game.rules.restart_taken(kind,0,9)
		game.strike(9,Vector3(0,0,-12))
		check(not game.rules.allows_goal(0) and game.restart_type=="KALE VURUŞU","Direct goal from "+kind+" is rejected")
	await arrange()
	game.rules.restart_taken("SERBEST VURUŞ",0,9)
	game.strike(9,Vector3(0,0,-12))
	check(game.rules.allows_goal(0),"A direct free kick can score without another touch")
	game.ball.place(Vector3(0,0.23,50.5))
	await frames(3)
	check(not game.rules.allows_goal(1) and game.restart_type=="KORNER" and game.restart_team==1,"Direct own goal from a restart awards a corner instead")
	await arrange()
	game.players[9].position=Vector3(5,0,-40)
	game.rules.foul(12,9)
	check(game.restart_type=="PENALTI" and game.restart_team==0,"Defender foul inside their penalty area awards a penalty")
	await arrange()
	game.players[9].position=Vector3(21,0,-40)
	game.rules.foul(12,9)
	check(game.restart_type=="SERBEST VURUŞ" and game.restart_team==0,"Foul outside the penalty-area width stays a free kick")
	await arrange()
	game.players[20].position=Vector3(-5,0,40)
	game.rules.foul(2,20)
	check(game.restart_type=="PENALTI" and game.restart_team==1,"Penalty decisions use the correct end for both teams")
	await arrange()
	game.rules.foul(12,9,true)
	check(game.players[12].yellow_cards==1 and game.players[12].visible,"A reckless challenge receives a yellow card")
	game.rules.foul(12,9,true)
	check(game.players[12].dismissed and not game.players[12].visible and game.players[12].collision_layer==0,"Second yellow dismisses the player and removes their physical body from play")
	game.reset_positions(0)
	check(not game.players[12].visible,"Kickoff does not restore a dismissed player")
	game.start_match(false,false)
	check(game.players[12].visible and game.players[12].yellow_cards==0,"New match clears disciplinary records")
	game.set_physics_process(false)
	for i in range(22): game.players[i].position=Vector3(-28+i*2,0,30)
	game.players[9].position=Vector3(0,0,0)
	game.players[12].position=Vector3(0,0,-0.8)
	game.ball.place(Vector3(0,0.23,-2))
	await frames(3)
	game.rules.start_tackle(9,Vector3.FORWARD)
	game.rules.resolve_tackles()
	check(game.state=="restart" and game.restart_team==1,"Swept tackle contact penalizes hitting an opponent before the ball")
	await arrange()
	game.players[9].position=Vector3(0,0,-20)
	game.ball.place(Vector3(0,0.23,-20.6))
	await frames(3)
	game.rules.start_tackle(9,Vector3.FORWARD)
	game.rules.resolve_tackles()
	check(game.state=="playing" and game.ball.pending_kick,"A ball-first slide plays the ball without inventing a foul")
	game.free()
	print("FOOTBALL RULES CHECK: %d failures" % failures)
	quit(0 if failures==0 else 1)
