extends SceneTree
var game
var failures := 0
func _initialize() -> void: call_deferred("run")
func check(ok: bool,label: String) -> void:
	if ok: print("PASS: "+label)
	else: failures+=1; push_error("FAIL: "+label)
func run() -> void:
	game=load("res://main.tscn").instantiate()
	root.add_child(game)
	await physics_frame
	game.set_physics_process(false)
	game.set_process(false)
	var audio=game.audio
	check(not audio.ambience.playing and not audio.cheering.playing,"Menu starts without unsolicited stadium sound")
	check(audio.menu_music.playing and audio.menu_music.volume_db<=-40,"Menu theme starts from silence rather than at full level")
	check(audio.menu_music.stream is AudioStreamMP3 and audio.menu_music.stream.loop and audio.menu_music.stream.get_length()>90,"Menu theme is the looping title recording")
	audio.update_atmosphere(0.4,"menu")
	check(audio.menu_music.playing and audio.menu_music.volume_db<-18,"The title theme eases in below match volume")
	check(audio.ambience.stream is AudioStreamMP3 and audio.ambience.stream.get_length()>150 and audio.ambience.stream.loop,"First supplied recording is a looping stadium ambience")
	check(audio.cheering.stream is AudioStreamMP3 and audio.cheering.stream.get_length()>16 and not audio.cheering.stream.loop,"Second supplied recording is a separate non-looping applause layer")
	check(audio.clips.whistle is AudioStreamWAV and audio.clips.whistle.get_length()>0.5 and audio.clips.whistle.get_length()<1,"Referee whistle uses the synthesized blast")
	game.start_match(false,false)
	check(audio.ambience.playing and not audio.cheering.playing and not audio.menu_music.playing,"Match starts the stadium ambience alone")
	check(audio.packed.size()==4 and audio.packed.all(func(bed): return bed.stream is AudioStreamMP3 and bed.stream.loop),"Packed stadium beds are four looping layers")
	check(audio.packed.all(func(bed): return bed.playing),"The four packed beds sit under the stadium at kickoff")
	game.stadium.react("shot",0,Vector3(0,0,-30))
	check(audio.cheering.playing and audio.ambience.playing and audio.cheer_kind=="shot","Actual shot event layers applause over uninterrupted ambience")
	check(audio.packed.all(func(bed): return bed.playing),"Applause sits on top of the packed beds without stopping them")
	audio.update_atmosphere(0.6,"playing")
	var age: float=audio.cheer_age
	game.stadium.react("shot",0,Vector3.ZERO)
	check(audio.cheer_age==age,"Repeated shots cannot stack or restart applause")
	game.stadium.react("save",1,Vector3.ZERO)
	check(audio.cheer_kind=="save" and audio.cheer_priority==3,"A save upgrades the active shot reaction")
	game.goal(0)
	check(audio.cheer_kind=="goal" and audio.cheer_priority==4,"Goal gets the strongest crowd reaction")
	check(audio.cheering.playing and audio.cheering.stream.get_length()>4 and audio.cheering.stream.get_length()<8,"Goal plays the dedicated celebration recording")
	check(audio.roar.playing and audio.roar.stream.get_length()>1 and not audio.roar.stream.loop,"Goal also plays a louder extra celebration layer")
	audio.update_atmosphere(0.15,"playing")
	check(audio.roar.playing and audio.cheering.playing and audio.roar.volume_db>audio.cheering.volume_db,"The extra celebration sits above the regular goal cheer")
	check(not audio.clips.has("goal"),"Synthetic goal noise is replaced by the supplied cheering")
	game.stadium.react("tackle",1,Vector3.ZERO)
	check(audio.cheer_kind=="goal","Lesser events cannot interrupt goal applause")
	audio.update_atmosphere(0.5,"playing")
	age=audio.cheer_age
	audio.update_atmosphere(1,"paused")
	check(audio.ambience.stream_paused and audio.cheering.stream_paused and audio.cheer_age==age,"Pause freezes both recordings and reaction timing")
	check(audio.packed.all(func(bed): return bed.stream_paused),"Pause also freezes the packed stadium beds")
	audio.update_atmosphere(0.1,"playing")
	check(not audio.ambience.stream_paused and not audio.cheering.stream_paused and audio.cheer_age>age,"Resume continues both recordings")
	audio.play("kick")
	check(audio.effects.playing and audio.cheering.playing,"Ball sounds keep their separate effect channel")
	audio.toggle()
	check(audio.ambience.volume_db<= -79 and not audio.cheering.playing and not audio.effects.playing,"M mutes stadium and applause along with the effects")
	check(audio.packed.all(func(bed): return bed.volume_db<=-79),"M also hushes the packed stadium beds")
	game.stadium.react("save",0,Vector3.ZERO)
	check(not audio.cheering.playing,"Muted events do not start queued applause")
	audio.toggle()
	audio.update_atmosphere(0.5,"playing")
	check(audio.ambience.playing and audio.ambience_gain>0 and not audio.cheering.playing,"Unmute fades ambience back without replaying an old event")
	audio.cheer_cooldown=0
	game.stadium.react("miss",0,Vector3.ZERO)
	check(audio.cheer_kind=="miss" and audio.cheering.playing,"An important missed chance can trigger a short reaction")
	for n in range(40): audio.update_atmosphere(0.1,"playing")
	check(not audio.cheering.playing and audio.ambience.playing,"Applause fades out while stadium ambience continues")
	audio.cheer_cooldown=0
	game.stadium.react("shot",0,Vector3.ZERO)
	game.stadium.react("foul",0,Vector3.ZERO)
	check(audio.cheer_kind=="foul" and audio.cheering.playing,"A whistled foul plays its own crowd reaction")
	check(audio.cheering.stream.get_length()>5 and audio.cheering.stream.get_length()<8,"Foul uses the supplied stadium recording")
	game.stadium.react("card",0,Vector3.ZERO)
	check(audio.cheer_kind=="card" and audio.cheering.playing,"A booking upgrades the foul reaction to the card recording")
	check(audio.cheering.stream.get_length()>1.5 and audio.cheering.stream.get_length()<3.5,"Card uses the supplied stadium recording")
	game.stadium.react("tackle",1,Vector3.ZERO)
	check(audio.cheer_kind=="card","Lesser events cannot interrupt a booking reaction")
	game.return_menu()
	check(not audio.ambience.playing and not audio.cheering.playing,"Returning to menu stops both recordings")
	check(audio.packed.all(func(bed): return not bed.playing),"Returning to menu also stops the packed stadium beds")
	check(audio.menu_music.playing and audio.menu_music.volume_db<=-40,"Returning to the menu restarts the title theme softly")
	game.start_match(false,false)
	check(audio.ambience.playing and not audio.cheering.playing and not audio.menu_music.playing and audio.cheer_priority==0,"A fresh match clears previous event playback")
	check(audio.drums.stream is AudioStreamMP3 and not audio.drums.stream.loop,"Supplied drum recording is a separate non-looping crowd layer")
	check(audio.drum_wait>=12 and audio.drum_wait<=22 and not audio.drums.playing,"First rhythm waits for a natural gap after kickoff")
	audio.drum_wait=0
	audio.update_atmosphere(0.1,"ceremony")
	check(not audio.drums.playing,"Rhythm does not start during the entrance ceremony")
	audio.update_atmosphere(0.1,"playing")
	check(audio.drums.playing and audio.ambience.playing and not audio.cheering.playing,"Drums occasionally play over the stadium bed")
	audio.update_atmosphere(0.8,"playing")
	var drum_age: float=audio.drum_age
	audio.update_atmosphere(1,"paused")
	check(audio.drums.stream_paused and audio.drum_age==drum_age,"Pause freezes the drum phrase and its timer")
	audio.update_atmosphere(0.1,"playing")
	game.stadium.react("shot",0,Vector3.ZERO)
	for n in range(5): audio.update_atmosphere(0.1,"playing")
	check(not audio.drums.playing and audio.cheering.playing,"Important play smoothly gives priority to applause")
	check(audio.drum_wait>=24 and audio.drum_wait<=42,"Next drum phrase has a spaced randomized delay")
	audio.drum_wait=0
	audio.update_atmosphere(0.1,"playing")
	check(not audio.drums.playing,"Ongoing applause blocks a new drum phrase")
	audio.start_match(true)
	audio.drum_wait=0
	audio.update_atmosphere(0.1,"playing")
	audio.toggle()
	check(not audio.drums.playing,"M also stops supporter drums")
	audio.toggle()
	audio.update_atmosphere(0.1,"playing")
	check(not audio.drums.playing,"Unmuting does not immediately restart drums")
	audio.drum_wait=0
	audio.update_atmosphere(0.1,"playing")
	for n in range(60): audio.update_atmosphere(0.1,"playing")
	check(not audio.drums.playing and audio.drum_wait>20,"A drum phrase ends and leaves a quiet gap")
	audio.drum_wait=0
	audio.update_atmosphere(0.1,"halftime")
	check(not audio.drums.playing,"No new rhythm starts during halftime")
	game.return_menu()
	check(not audio.drums.playing and audio.drum_duration==0,"Menu clears drum playback and scheduling")
	check(audio.menu_music.playing,"The title theme returns with the menu")
	game.start_match(false,false)
	check(audio.chants.size()==3 and audio.chants.all(func(voice): return voice.stream is AudioStreamMP3 and not voice.stream.loop),"Terrace chants are three separate non-looping crowd layers")
	check(audio.chant_wait[0]>=16 and audio.chant_wait[0]<=28 and not audio.chants[0].playing,"First chant waits behind the stadium bed after kickoff")
	audio.chant_wait[0]=0
	audio.update_atmosphere(0.1,"ceremony")
	check(not audio.chants[0].playing,"Chants do not start during the entrance ceremony")
	audio.update_atmosphere(0.1,"playing")
	check(audio.chants[0].playing and audio.ambience.playing,"A terrace chant fades in over the stadium bed")
	audio.start_chant(1)
	check(audio.chants[0].playing and audio.chants[1].playing,"Two chants can sit together in the background")
	audio.drum_wait=0
	audio.update_atmosphere(0.1,"playing")
	check(audio.drums.playing and audio.chants[0].playing,"Drums and a chant can play together")
	var chant_age: float=audio.chant_age[0]
	audio.update_atmosphere(1,"paused")
	check(audio.chants[0].stream_paused and audio.chant_age[0]==chant_age,"Pause freezes the chant phrase")
	audio.update_atmosphere(0.1,"playing")
	game.stadium.react("shot",0,Vector3.ZERO)
	for n in range(6): audio.update_atmosphere(0.1,"playing")
	check(not audio.chants[0].playing and audio.cheering.playing,"Important play fades a chant under applause")
	game.return_menu()
	check(audio.chants.all(func(voice): return not voice.playing) and audio.chant_duration[0]==0,"Menu clears chant playback")
	game.start_match()
	check(game.state=="ceremony" and audio.walkout.playing and audio.ambience.playing,"Teams entering play the pre-match crowd bed")
	audio.update_atmosphere(0.25,"ceremony")
	check(audio.walkout.volume_db>-40 and not audio.cheering.playing,"Walkout crowd sits over the stadium without starting applause")
	game.stadium.react("entrance",0,Vector3.ZERO)
	check(audio.walkout.playing and audio.cheer_kind!="entrance","A second tunnel reaction does not restart the walkout bed")
	game.ceremony.finish(true)
	check(audio.walkout_duration<=audio.walkout_age+1.41,"Skipping the ceremony starts a fade of the walkout bed")
	game.return_menu()
	check(not audio.walkout.playing and audio.walkout_duration==0,"Menu clears the walkout crowd")
	game.start_match(false,false)
	audio.start_replay_chant(1)
	check(not audio.replay_chant.playing,"An away goal replay does not start the home terrace chant")
	audio.start_replay_chant(0)
	audio.update_atmosphere(0.2,"replay")
	check(audio.replay_chant.playing and audio.replay_chant.volume_db<-12,"Goal replay sits a quiet home chant underneath")
	audio.release_replay_chant()
	check(audio.replay_duration<=audio.replay_age+0.81,"Leaving the replay fades the home chant")
	game.return_menu()
	check(not audio.replay_chant.playing,"Menu clears the replay chant")
	game.start_match(false,false)
	audio.crowd_context(0.4,0.0,0.0,0,0.3,0)
	for n in range(8): audio.update_atmosphere(0.1,"playing")
	check(audio.swells.size()==4 and audio.swell_pressure<0.05,"Build-up stays silent when the ball is not in a dangerous area")
	audio.crowd_context(0.4,0.32,0.0,0,0.3,0)
	for n in range(22): audio.update_atmosphere(0.1,"playing")
	check(audio.swell_pressure>0.18 and audio.swell_gain[0]>audio.swell_gain[3],"A half-chance only lifts the first terrace layers")
	audio.crowd_context(0.4,0.88,0.0,0,0.3,0)
	for n in range(28): audio.update_atmosphere(0.1,"playing")
	check(audio.swell_pressure>0.7 and audio.swells[3].volume_db>-40 and audio.swells[3].volume_db<-12,"A box approach stands the crowd up without a goal shout")
	audio.crowd_context(0.4,0.0,0.0,0,0.3,0)
	for n in range(12): audio.update_atmosphere(0.1,"playing")
	check(audio.swell_pressure<0.25,"Breaking the attack lets the crowd sit back down")
	game.return_menu()
	check(audio.swells.all(func(rise): return not rise.playing) and audio.swell_pressure==0,"Menu clears the build-up layers")
	game.start_match(true)
	check(not audio.ambience.playing and not audio.cheering.playing and not audio.menu_music.playing,"Solo training keeps its existing sound behavior")
	check(audio.packed.all(func(bed): return not bed.playing),"Solo training also keeps the packed beds off")
	print("STADIUM AUDIO CHECK: %d failures" % failures)
	game.free()
	quit(0 if failures==0 else 1)
