extends RefCounted
## Generated by tools/build_commentary_audio.py; synthetic Turkish voices.
const CUES := {
	"kickoff": [
		{
			"text": "Ve maç başlıyor! Güzel bir mücadele olsun.",
			"clip": "res://assets/audio/commentary/kickoff_01_spiker.wav",
			"reply": "İlk dakikalarda iki takımın baskıya nasıl cevap vereceğini göreceğiz.",
			"reply_clip": "res://assets/audio/commentary/kickoff_01_yorumcu.wav"
		},
		{
			"text": "Düdük geldi, top oyunda!",
			"clip": "res://assets/audio/commentary/kickoff_02_spiker.wav",
			"reply": "Evet, şimdi sahada söz oyuncularda. İyi seyirler.",
			"reply_clip": "res://assets/audio/commentary/kickoff_02_yorumcu.wav"
		}
	],
	"second_half": [
		{
			"text": "İkinci yarı başladı. Yeniden birlikteyiz.",
			"clip": "res://assets/audio/commentary/second_half_01_spiker.wav",
			"reply": "Bakalım devre arasındaki hamleler oyuna nasıl yansıyacak.",
			"reply_clip": "res://assets/audio/commentary/second_half_01_yorumcu.wav"
		},
		{
			"text": "Takımlar döndü, ikinci yarının ilk pası verildi.",
			"clip": "res://assets/audio/commentary/second_half_02_spiker.wav",
			"reply": "Şimdi oyunun ritmini yeniden bulmak gerekiyor.",
			"reply_clip": "res://assets/audio/commentary/second_half_02_yorumcu.wav"
		}
	],
	"goal": [
		{
			"text": "Gol! Top ağlarda!",
			"clip": "res://assets/audio/commentary/goal_01_spiker.wav",
			"reply": "Böyle anlarda bütün emek o son vuruşa bakıyor.",
			"reply_clip": "res://assets/audio/commentary/goal_01_yorumcu.wav"
		},
		{
			"text": "Ve gol! Ağlar havalandı!",
			"clip": "res://assets/audio/commentary/goal_02_spiker.wav",
			"reply": "Gol geldi. Şimdi iki takımın vereceği tepki önemli.",
			"reply_clip": "res://assets/audio/commentary/goal_02_yorumcu.wav"
		},
		{
			"text": "Gol! Bitirdi işi!",
			"clip": "res://assets/audio/commentary/goal_03_spiker.wav",
			"reply": "Evet, bu pozisyonun sonunda gülen taraf hücum eden takım.",
			"reply_clip": "res://assets/audio/commentary/goal_03_yorumcu.wav"
		}
	],
	"goal_level": [
		{
			"text": "Gol! Yeniden eşitlik!",
			"clip": "res://assets/audio/commentary/goal_level_01_spiker.wav",
			"reply": "Maça yeniden ortak oldular. Şimdi psikolojik denge de değişebilir.",
			"reply_clip": "res://assets/audio/commentary/goal_level_01_yorumcu.wav"
		},
		{
			"text": "Top ağlarda! Skora denge geliyor!",
			"clip": "res://assets/audio/commentary/goal_level_02_spiker.wav",
			"reply": "Evet, bu golle her şey yeniden başlıyor.",
			"reply_clip": "res://assets/audio/commentary/goal_level_02_yorumcu.wav"
		},
		{
			"text": "Ve gol! Beraberliği yakalıyorlar!",
			"clip": "res://assets/audio/commentary/goal_level_03_spiker.wav",
			"reply": "Artık iki takım da galibiyet golünü düşünecek.",
			"reply_clip": "res://assets/audio/commentary/goal_level_03_yorumcu.wav"
		}
	],
	"goal_lead": [
		{
			"text": "Gol! Öne geçiyorlar!",
			"clip": "res://assets/audio/commentary/goal_lead_01_spiker.wav",
			"reply": "Şimdi rakibin biraz daha risk alması gerekecek.",
			"reply_clip": "res://assets/audio/commentary/goal_lead_01_yorumcu.wav"
		},
		{
			"text": "Ve gol! Skor üstünlüğünü alıyorlar!",
			"clip": "res://assets/audio/commentary/goal_lead_02_spiker.wav",
			"reply": "Evet, avantaj onlarda. Ama oyundan kopmamak gerekiyor.",
			"reply_clip": "res://assets/audio/commentary/goal_lead_02_yorumcu.wav"
		},
		{
			"text": "Top ağlarda! Üstünlük geliyor!",
			"clip": "res://assets/audio/commentary/goal_lead_03_spiker.wav",
			"reply": "Bu gol maçın gidişatını değiştirebilir.",
			"reply_clip": "res://assets/audio/commentary/goal_lead_03_yorumcu.wav"
		}
	],
	"goal_extend": [
		{
			"text": "Gol! Farkı açıyorlar!",
			"clip": "res://assets/audio/commentary/goal_extend_01_spiker.wav",
			"reply": "Rakip için geri dönüş artık biraz daha zor.",
			"reply_clip": "res://assets/audio/commentary/goal_extend_01_yorumcu.wav"
		},
		{
			"text": "Ve gol! Avantaj büyüyor!",
			"clip": "res://assets/audio/commentary/goal_extend_02_spiker.wav",
			"reply": "Evet, skor rahatlatıyor ama disiplin hâlâ önemli.",
			"reply_clip": "res://assets/audio/commentary/goal_extend_02_yorumcu.wav"
		}
	],
	"goal_reply": [
		{
			"text": "Gol! Fark azalıyor!",
			"clip": "res://assets/audio/commentary/goal_reply_01_spiker.wav",
			"reply": "Geri dönüş için ihtiyaç duydukları moral bu olabilir.",
			"reply_clip": "res://assets/audio/commentary/goal_reply_01_yorumcu.wav"
		},
		{
			"text": "Top ağlarda! Arayı kapatıyorlar!",
			"clip": "res://assets/audio/commentary/goal_reply_02_spiker.wav",
			"reply": "Henüz eşitlik yok ama yeniden umutlandılar.",
			"reply_clip": "res://assets/audio/commentary/goal_reply_02_yorumcu.wav"
		}
	],
	"goal_late_lead": [
		{
			"text": "Gol! Son bölümde öne geçiyorlar!",
			"clip": "res://assets/audio/commentary/goal_late_lead_01_spiker.wav",
			"reply": "Rakibin cevap vermek için çok az zamanı var.",
			"reply_clip": "res://assets/audio/commentary/goal_late_lead_01_yorumcu.wav"
		},
		{
			"text": "Ve gol! Bitime doğru çok önemli bir gol!",
			"clip": "res://assets/audio/commentary/goal_late_lead_02_spiker.wav",
			"reply": "Evet, şimdi kalan dakikaları çok akıllı oynamak gerekiyor.",
			"reply_clip": "res://assets/audio/commentary/goal_late_lead_02_yorumcu.wav"
		}
	],
	"goal_late_level": [
		{
			"text": "Gol! Son bölümde eşitlik!",
			"clip": "res://assets/audio/commentary/goal_late_level_01_spiker.wav",
			"reply": "Tam da umutlar azalırken geldi bu gol.",
			"reply_clip": "res://assets/audio/commentary/goal_late_level_01_yorumcu.wav"
		},
		{
			"text": "Top ağlarda! Bitime doğru beraberlik!",
			"clip": "res://assets/audio/commentary/goal_late_level_02_spiker.wav",
			"reply": "Evet, son dakikalarda maç yeniden açıldı.",
			"reply_clip": "res://assets/audio/commentary/goal_late_level_02_yorumcu.wav"
		}
	],
	"own_goal": [
		{
			"text": "Kendi kalesine! Çok talihsiz bir an.",
			"clip": "res://assets/audio/commentary/own_goal_01_spiker.wav",
			"reply": "Böyle bir anda takım arkadaşlarının desteği çok önemli.",
			"reply_clip": "res://assets/audio/commentary/own_goal_01_yorumcu.wav"
		},
		{
			"text": "Top kendi ağlarına gidiyor!",
			"clip": "res://assets/audio/commentary/own_goal_02_spiker.wav",
			"reply": "İstemediği bir sonuç. Şimdi bu pozisyonu geride bırakmalı.",
			"reply_clip": "res://assets/audio/commentary/own_goal_02_yorumcu.wav"
		}
	],
	"shot": [
		{
			"text": "Vurdu!",
			"clip": "res://assets/audio/commentary/shot_01_spiker.wav",
			"reply": "",
			"reply_clip": ""
		},
		{
			"text": "Kaleyi deniyor!",
			"clip": "res://assets/audio/commentary/shot_02_spiker.wav",
			"reply": "",
			"reply_clip": ""
		},
		{
			"text": "Şut geliyor!",
			"clip": "res://assets/audio/commentary/shot_03_spiker.wav",
			"reply": "",
			"reply_clip": ""
		},
		{
			"text": "Vuruşunu yaptı!",
			"clip": "res://assets/audio/commentary/shot_04_spiker.wav",
			"reply": "",
			"reply_clip": ""
		}
	],
	"shot_high": [
		{
			"text": "Top üstten dışarıda.",
			"clip": "res://assets/audio/commentary/shot_high_01_spiker.wav",
			"reply": "Bu kez vuruşun yüksekliğini ayarlayamadı.",
			"reply_clip": "res://assets/audio/commentary/shot_high_01_yorumcu.wav"
		},
		{
			"text": "Yükseldi top, aut.",
			"clip": "res://assets/audio/commentary/shot_high_02_spiker.wav",
			"reply": "Kaleyi bulsa tehlike yaratabilirdi.",
			"reply_clip": "res://assets/audio/commentary/shot_high_02_yorumcu.wav"
		},
		{
			"text": "Çerçevenin üzerinden dışarıya.",
			"clip": "res://assets/audio/commentary/shot_high_03_spiker.wav",
			"reply": "",
			"reply_clip": ""
		}
	],
	"shot_wide": [
		{
			"text": "Top yandan dışarıda.",
			"clip": "res://assets/audio/commentary/shot_wide_01_spiker.wav",
			"reply": "Son vuruşta istediği yönü bulamadı.",
			"reply_clip": "res://assets/audio/commentary/shot_wide_01_yorumcu.wav"
		},
		{
			"text": "Direğin yanından auta gidiyor.",
			"clip": "res://assets/audio/commentary/shot_wide_02_spiker.wav",
			"reply": "Biraz daha isabetli bir vuruş gerekiyordu.",
			"reply_clip": "res://assets/audio/commentary/shot_wide_02_yorumcu.wav"
		},
		{
			"text": "Kaleyi bulamadı.",
			"clip": "res://assets/audio/commentary/shot_wide_03_spiker.wav",
			"reply": "",
			"reply_clip": ""
		}
	],
	"save": [
		{
			"text": "Kaleci yerinde!",
			"clip": "res://assets/audio/commentary/save_01_spiker.wav",
			"reply": "Vuruşu karşıladı, takımını oyunda tutuyor.",
			"reply_clip": "res://assets/audio/commentary/save_01_yorumcu.wav"
		},
		{
			"text": "Kaleciden kurtarış!",
			"clip": "res://assets/audio/commentary/save_02_spiker.wav",
			"reply": "Evet, bu kez kaleciyi geçemediler.",
			"reply_clip": "res://assets/audio/commentary/save_02_yorumcu.wav"
		},
		{
			"text": "Kaleci gole izin vermiyor!",
			"clip": "res://assets/audio/commentary/save_03_spiker.wav",
			"reply": "",
			"reply_clip": ""
		},
		{
			"text": "Vuruşu kaleci karşılıyor!",
			"clip": "res://assets/audio/commentary/save_04_spiker.wav",
			"reply": "",
			"reply_clip": ""
		}
	],
	"great_save": [
		{
			"text": "Müthiş kurtarış! Kaleci harika uzandı!",
			"clip": "res://assets/audio/commentary/great_save_01_spiker.wav",
			"reply": "Gerçekten önemli bir top çıkardı. Takımına nefes aldırdı.",
			"reply_clip": "res://assets/audio/commentary/great_save_01_yorumcu.wav"
		},
		{
			"text": "Ne kurtarış ama! Gole izin vermedi!",
			"clip": "res://assets/audio/commentary/great_save_02_spiker.wav",
			"reply": "Böyle kurtarışlar takımın güvenini de artırır.",
			"reply_clip": "res://assets/audio/commentary/great_save_02_yorumcu.wav"
		}
	],
	"woodwork": [
		{
			"text": "Direk! Top geri geldi!",
			"clip": "res://assets/audio/commentary/woodwork_01_spiker.wav",
			"reply": "Küçücük bir farkla gol kaçtı.",
			"reply_clip": "res://assets/audio/commentary/woodwork_01_yorumcu.wav"
		},
		{
			"text": "Direğe takıldı!",
			"clip": "res://assets/audio/commentary/woodwork_02_spiker.wav",
			"reply": "Evet, çerçeve bu kez golü önledi.",
			"reply_clip": "res://assets/audio/commentary/woodwork_02_yorumcu.wav"
		},
		{
			"text": "Top direkten dönüyor!",
			"clip": "res://assets/audio/commentary/woodwork_03_spiker.wav",
			"reply": "",
			"reply_clip": ""
		}
	],
	"corner": [
		{
			"text": "Korner. Duran toptan gelecekler.",
			"clip": "res://assets/audio/commentary/corner_01_spiker.wav",
			"reply": "Ceza sahasında paylaşım çok önemli olacak.",
			"reply_clip": "res://assets/audio/commentary/corner_01_yorumcu.wav"
		},
		{
			"text": "Köşe vuruşu kazanıldı.",
			"clip": "res://assets/audio/commentary/corner_02_spiker.wav",
			"reply": "İlk top kadar seken topa da hazır olmak gerekiyor.",
			"reply_clip": "res://assets/audio/commentary/corner_02_yorumcu.wav"
		},
		{
			"text": "Top kornere çıktı.",
			"clip": "res://assets/audio/commentary/corner_03_spiker.wav",
			"reply": "",
			"reply_clip": ""
		}
	],
	"free_kick": [
		{
			"text": "Serbest vuruş. Topun başına geçiyorlar.",
			"clip": "res://assets/audio/commentary/free_kick_01_spiker.wav",
			"reply": "Duran toplar oyunun dengesini değiştirebilir.",
			"reply_clip": "res://assets/audio/commentary/free_kick_01_yorumcu.wav"
		},
		{
			"text": "Düdük çaldı, serbest vuruş.",
			"clip": "res://assets/audio/commentary/free_kick_02_spiker.wav",
			"reply": "",
			"reply_clip": ""
		}
	],
	"penalty": [
		{
			"text": "Penaltı! Hakem beyaz noktayı gösteriyor!",
			"clip": "res://assets/audio/commentary/penalty_01_spiker.wav",
			"reply": "Şimdi bütün baskı topun başına gelecek oyuncuda.",
			"reply_clip": "res://assets/audio/commentary/penalty_01_yorumcu.wav"
		},
		{
			"text": "Karar penaltı!",
			"clip": "res://assets/audio/commentary/penalty_02_spiker.wav",
			"reply": "Vuran oyuncuyla kaleci arasında bir sinir mücadelesi olacak.",
			"reply_clip": "res://assets/audio/commentary/penalty_02_yorumcu.wav"
		}
	],
	"offside": [
		{
			"text": "Bayrak havada. Ofsayt.",
			"clip": "res://assets/audio/commentary/offside_01_spiker.wav",
			"reply": "Koşunun zamanlaması belirleyici oldu.",
			"reply_clip": "res://assets/audio/commentary/offside_01_yorumcu.wav"
		},
		{
			"text": "Hücum ofsaytla kesiliyor.",
			"clip": "res://assets/audio/commentary/offside_02_spiker.wav",
			"reply": "",
			"reply_clip": ""
		}
	],
	"yellow": [
		{
			"text": "Sarı kart çıktı.",
			"clip": "res://assets/audio/commentary/yellow_01_spiker.wav",
			"reply": "Artık müdahalelerinde daha dikkatli olmak zorunda.",
			"reply_clip": "res://assets/audio/commentary/yellow_01_yorumcu.wav"
		},
		{
			"text": "Hakem sarı kartını gösteriyor.",
			"clip": "res://assets/audio/commentary/yellow_02_spiker.wav",
			"reply": "Bir kart daha görme riskini düşünerek oynamalı.",
			"reply_clip": "res://assets/audio/commentary/yellow_02_yorumcu.wav"
		}
	],
	"red": [
		{
			"text": "Kırmızı kart! Takım eksik kalıyor!",
			"clip": "res://assets/audio/commentary/red_01_spiker.wav",
			"reply": "Şimdi sahadaki yerleşimi yeniden düşünmeleri gerekecek.",
			"reply_clip": "res://assets/audio/commentary/red_01_yorumcu.wav"
		},
		{
			"text": "Oyundan atılıyor! Karar kırmızı kart!",
			"clip": "res://assets/audio/commentary/red_02_spiker.wav",
			"reply": "Bir kişi eksik oynamak kalan oyuncuların yükünü artıracak.",
			"reply_clip": "res://assets/audio/commentary/red_02_yorumcu.wav"
		}
	],
	"handball": [
		{
			"text": "Elle oynama! Düdük geliyor.",
			"clip": "res://assets/audio/commentary/handball_01_spiker.wav",
			"reply": "",
			"reply_clip": ""
		},
		{
			"text": "Hakem el temasını gördü, oyun duruyor.",
			"clip": "res://assets/audio/commentary/handball_02_spiker.wav",
			"reply": "",
			"reply_clip": ""
		}
	],
	"injury": [
		{
			"text": "Bir sakatlık işareti var.",
			"clip": "res://assets/audio/commentary/injury_01_spiker.wav",
			"reply": "Sağlık durumunu görmeden devamı için bir şey söylemek zor.",
			"reply_clip": "res://assets/audio/commentary/injury_01_yorumcu.wav"
		},
		{
			"text": "Rahat hareket edemiyor. Bir sıkıntısı var.",
			"clip": "res://assets/audio/commentary/injury_02_spiker.wav",
			"reply": "Teknik ekip oyuncunun durumunu yakından izleyecektir.",
			"reply_clip": "res://assets/audio/commentary/injury_02_yorumcu.wav"
		}
	],
	"halftime": [
		{
			"text": "İlk yarı sona erdi. Kısa bir ara.",
			"clip": "res://assets/audio/commentary/halftime_01_spiker.wav",
			"reply": "İki teknik ekip için de oyunu yeniden değerlendirme zamanı.",
			"reply_clip": "res://assets/audio/commentary/halftime_01_yorumcu.wav"
		},
		{
			"text": "Devre arası düdüğü geldi.",
			"clip": "res://assets/audio/commentary/halftime_02_spiker.wav",
			"reply": "Bakalım ikinci yarıya nasıl dönecekler.",
			"reply_clip": "res://assets/audio/commentary/halftime_02_yorumcu.wav"
		}
	],
	"fulltime": [
		{
			"text": "Son düdük! Maç sona erdi.",
			"clip": "res://assets/audio/commentary/fulltime_01_spiker.wav",
			"reply": "Sahadaki mücadele burada bitti. Bizimle olduğunuz için teşekkürler.",
			"reply_clip": "res://assets/audio/commentary/fulltime_01_yorumcu.wav"
		},
		{
			"text": "Ve maç bitti!",
			"clip": "res://assets/audio/commentary/fulltime_02_spiker.wav",
			"reply": "Bir karşılaşmayı daha geride bıraktık. Görüşmek üzere.",
			"reply_clip": "res://assets/audio/commentary/fulltime_02_yorumcu.wav"
		}
	],
	"substitution": [
		{
			"text": "Kenardan bir oyuncu değişikliği geliyor.",
			"clip": "res://assets/audio/commentary/substitution_01_spiker.wav",
			"reply": "Taze bir oyuncu oyunun temposunu değiştirebilir.",
			"reply_clip": "res://assets/audio/commentary/substitution_01_yorumcu.wav"
		},
		{
			"text": "Oyuncu değişikliği. Yeni bir isim sahada.",
			"clip": "res://assets/audio/commentary/substitution_02_spiker.wav",
			"reply": "Bakalım bu hamle oyuna nasıl yansıyacak.",
			"reply_clip": "res://assets/audio/commentary/substitution_02_yorumcu.wav"
		}
	],
	"substitution_named": [
		{
			"text": "Oyuncu değişikliği yapılıyor.",
			"clip": "res://assets/audio/commentary/substitution_named_01_spiker.wav",
			"reply": "Yeni giren oyuncunun maça hemen uyum sağlaması önemli.",
			"reply_clip": "res://assets/audio/commentary/substitution_named_01_yorumcu.wav"
		},
		{
			"text": "Yedek kulübesinden bir hamle geliyor.",
			"clip": "res://assets/audio/commentary/substitution_named_02_spiker.wav",
			"reply": "Taze kuvvetle oyuna yeni bir yön vermek istiyorlar.",
			"reply_clip": "res://assets/audio/commentary/substitution_named_02_yorumcu.wav"
		}
	],
	"long_shot": [
		{
			"text": "Uzaktan deniyor!",
			"clip": "res://assets/audio/commentary/long_shot_01_spiker.wav",
			"reply": "",
			"reply_clip": ""
		},
		{
			"text": "Mesafeye bakmadan vurdu!",
			"clip": "res://assets/audio/commentary/long_shot_02_spiker.wav",
			"reply": "",
			"reply_clip": ""
		},
		{
			"text": "Uzaklardan bir şut!",
			"clip": "res://assets/audio/commentary/long_shot_03_spiker.wav",
			"reply": "",
			"reply_clip": ""
		}
	],
	"header": [
		{
			"text": "Kafa vuruşu!",
			"clip": "res://assets/audio/commentary/header_01_spiker.wav",
			"reply": "",
			"reply_clip": ""
		},
		{
			"text": "Kafayla kaleyi deniyor!",
			"clip": "res://assets/audio/commentary/header_02_spiker.wav",
			"reply": "",
			"reply_clip": ""
		},
		{
			"text": "Yükseldi, kafayı vurdu!",
			"clip": "res://assets/audio/commentary/header_03_spiker.wav",
			"reply": "",
			"reply_clip": ""
		}
	],
	"volley": [
		{
			"text": "Gelişine vurdu!",
			"clip": "res://assets/audio/commentary/volley_01_spiker.wav",
			"reply": "",
			"reply_clip": ""
		},
		{
			"text": "Bekletmeden kaleye!",
			"clip": "res://assets/audio/commentary/volley_02_spiker.wav",
			"reply": "",
			"reply_clip": ""
		},
		{
			"text": "Topu kontrol etmeden vuruyor!",
			"clip": "res://assets/audio/commentary/volley_03_spiker.wav",
			"reply": "",
			"reply_clip": ""
		}
	],
	"cross": [
		{
			"text": "Orta geliyor!",
			"clip": "res://assets/audio/commentary/cross_01_spiker.wav",
			"reply": "",
			"reply_clip": ""
		},
		{
			"text": "Ceza sahasına bir orta!",
			"clip": "res://assets/audio/commentary/cross_02_spiker.wav",
			"reply": "",
			"reply_clip": ""
		},
		{
			"text": "Topu içeriye gönderdi!",
			"clip": "res://assets/audio/commentary/cross_03_spiker.wav",
			"reply": "",
			"reply_clip": ""
		}
	],
	"skill": [
		{
			"text": "Şık bir hareket!",
			"clip": "res://assets/audio/commentary/skill_01_spiker.wav",
			"reply": "",
			"reply_clip": ""
		},
		{
			"text": "Topla güzel bir hareket deniyor.",
			"clip": "res://assets/audio/commentary/skill_02_spiker.wav",
			"reply": "",
			"reply_clip": ""
		},
		{
			"text": "Bileklerini kullanıyor.",
			"clip": "res://assets/audio/commentary/skill_03_spiker.wav",
			"reply": "",
			"reply_clip": ""
		}
	],
	"counter": [
		{
			"text": "Topu kazandılar, hızla çıkıyorlar!",
			"clip": "res://assets/audio/commentary/counter_01_spiker.wav",
			"reply": "Savunma yerleşmeden boş alanı kullanmak isteyecekler.",
			"reply_clip": "res://assets/audio/commentary/counter_01_yorumcu.wav"
		},
		{
			"text": "Şimdi hızlı hücum fırsatı!",
			"clip": "res://assets/audio/commentary/counter_02_spiker.wav",
			"reply": "İlk pasın yönü bu hücum için çok önemli.",
			"reply_clip": "res://assets/audio/commentary/counter_02_yorumcu.wav"
		}
	],
	"wing_attack": [
		{
			"text": "Hücumu kanada taşıdılar.",
			"clip": "res://assets/audio/commentary/wing_attack_01_spiker.wav",
			"reply": "Evet, buradan savunmayı genişletip içeride alan arayabilirler.",
			"reply_clip": "res://assets/audio/commentary/wing_attack_01_yorumcu.wav"
		},
		{
			"text": "Bu kez kenardan geliyorlar.",
			"clip": "res://assets/audio/commentary/wing_attack_02_spiker.wav",
			"reply": "Ceza sahasındaki koşularla pasın zamanlaması örtüşmeli.",
			"reply_clip": "res://assets/audio/commentary/wing_attack_02_yorumcu.wav"
		}
	],
	"pressure": [
		{
			"text": "Ceza sahası çevresinde çoğaldılar.",
			"clip": "res://assets/audio/commentary/pressure_01_spiker.wav",
			"reply": "Savunma için asıl mesele oyuncular arasındaki boşlukları kapatmak.",
			"reply_clip": "res://assets/audio/commentary/pressure_01_yorumcu.wav"
		},
		{
			"text": "Hücumda destek var, baskıyı sürdürüyorlar.",
			"clip": "res://assets/audio/commentary/pressure_02_spiker.wav",
			"reply": "Evet, topu kaybederlerse arkalarında bırakacakları alana da dikkat etmeliler.",
			"reply_clip": "res://assets/audio/commentary/pressure_02_yorumcu.wav"
		}
	],
	"build_up": [
		{
			"text": "Topu tutuyorlar. Sakin bir hazırlık var.",
			"clip": "res://assets/audio/commentary/build_up_01_spiker.wav",
			"reply": "Bazen doğru pas için bir an daha beklemek gerekir.",
			"reply_clip": "res://assets/audio/commentary/build_up_01_yorumcu.wav"
		},
		{
			"text": "Acele etmiyorlar, boşluk arıyorlar.",
			"clip": "res://assets/audio/commentary/build_up_02_spiker.wav",
			"reply": "Evet, topu dolaştırarak rakibi yerinden çıkarmaya çalışabilirler.",
			"reply_clip": "res://assets/audio/commentary/build_up_02_yorumcu.wav"
		}
	],
	"late_chase": [
		{
			"text": "Son bölümde eşitlik arıyorlar.",
			"clip": "res://assets/audio/commentary/late_chase_01_spiker.wav",
			"reply": "Risk almaları gerekiyor ama topu aceleyle kaybetmemeliler.",
			"reply_clip": "res://assets/audio/commentary/late_chase_01_yorumcu.wav"
		},
		{
			"text": "Tek gol gerideler, süre azalıyor.",
			"clip": "res://assets/audio/commentary/late_chase_02_spiker.wav",
			"reply": "Evet, kalan her hücumu iyi değerlendirmek zorundalar.",
			"reply_clip": "res://assets/audio/commentary/late_chase_02_yorumcu.wav"
		}
	],
	"late_protect": [
		{
			"text": "Son bölümde top öndeki takımda.",
			"clip": "res://assets/audio/commentary/late_protect_01_spiker.wav",
			"reply": "Topu saklamak kadar güvenli pas seçmek de değerli.",
			"reply_clip": "res://assets/audio/commentary/late_protect_01_yorumcu.wav"
		},
		{
			"text": "Skor avantajı onlarda, topu tutuyorlar.",
			"clip": "res://assets/audio/commentary/late_protect_02_spiker.wav",
			"reply": "Evet, böyle anlarda gereksiz bir top kaybı pahalıya çıkabilir.",
			"reply_clip": "res://assets/audio/commentary/late_protect_02_yorumcu.wav"
		}
	],
	"late_level": [
		{
			"text": "Son bölümde skor eşit. Her atak önemli.",
			"clip": "res://assets/audio/commentary/late_level_01_spiker.wav",
			"reply": "Bir gol bütün hesabı değiştirebilir. Sabırla cesareti dengelemek gerekiyor.",
			"reply_clip": "res://assets/audio/commentary/late_level_01_yorumcu.wav"
		},
		{
			"text": "Bitime yaklaşıyoruz, denge henüz bozulmadı.",
			"clip": "res://assets/audio/commentary/late_level_02_spiker.wav",
			"reply": "Evet, küçük bir hata bile sonucu belirleyebilir.",
			"reply_clip": "res://assets/audio/commentary/late_level_02_yorumcu.wav"
		}
	],
	"fatigue": [
		{
			"text": "Yorgunluk belirginleşiyor.",
			"clip": "res://assets/audio/commentary/fatigue_01_spiker.wav",
			"reply": "Taze bir oyuncu özellikle savunmaya dönüşlerde fark yaratabilir.",
			"reply_clip": "res://assets/audio/commentary/fatigue_01_yorumcu.wav"
		},
		{
			"text": "Kalan enerjiyi iyi kullanmak gerekiyor.",
			"clip": "res://assets/audio/commentary/fatigue_02_spiker.wav",
			"reply": "Evet, artık hangi koşuyu yapacaklarına daha dikkatli karar vermeliler.",
			"reply_clip": "res://assets/audio/commentary/fatigue_02_yorumcu.wav"
		}
	],
	"rain": [
		{
			"text": "Yağmurda pasın şiddeti daha da önemli.",
			"clip": "res://assets/audio/commentary/rain_01_spiker.wav",
			"reply": "Top yerde hız kaybediyor. Kısa kalan pas baskı getirebilir.",
			"reply_clip": "res://assets/audio/commentary/rain_01_yorumcu.wav"
		},
		{
			"text": "Islak zeminde topu iyi hesaplamak gerekiyor.",
			"clip": "res://assets/audio/commentary/rain_02_spiker.wav",
			"reply": "Evet, pası alan oyuncunun da topa doğru hareketlenmesi önemli.",
			"reply_clip": "res://assets/audio/commentary/rain_02_yorumcu.wav"
		}
	]
}
