extends RefCounted
## Short Turkish calls. Tactical remarks are selected only from observed play.
const LINES := {
	"kickoff":["Ve maç başlıyor!","Hakemin düdüğüyle mücadele başladı.","Santra yapıldı, top oyunda.","İlk pas verildi, iyi seyirler.","İki takım da hazır, mücadele başladı.","Başlama düdüğü geldi!"],
	"second_half":["İkinci yarı başladı.","Yeniden top oyunda, ikinci yarıdayız.","İkinci yarının ilk pası verildi.","Takımlar döndü, mücadele kaldığı yerden sürüyor.","Düdük çaldı, ikinci yarı başlıyor."],
	"goal":["Gol! {name} ağları sarsıyor!","Ve gol! {name}!","Gol! {name} bitiriyor!","{name} vurdu, gol oldu!","Top ağlarda! Golün sahibi {name}!","Gol geliyor! {name}!"],
	"goal_level":["Gol! {name}, yeniden eşitlik!","{name} atıyor! Skor eşitlendi!","Top ağlarda! {name} maça dengeyi getiriyor!","Gol! {name} ile beraberlik geliyor!"],
	"goal_lead":["Gol! {name}, takımını öne geçiriyor!","{name} atıyor! Üstünlük şimdi onlarda!","Gol! {name} ile öne geçiyorlar!","Top ağlarda! {name}, skor avantajını getiriyor!"],
	"goal_extend":["Gol! {name}, fark açılıyor!","{name} ağları buluyor, fark büyüyor!","Gol! {name} ile avantajlarını artırıyorlar!","Top ağlarda! {name}, farkı artıran golü atıyor!"],
	"goal_reply":["Gol! {name}, fark azalıyor!","{name} atıyor! Geri dönüş için bir adım!","Top ağlarda! {name} ile farkı azaltıyorlar!","Gol! {name}, rakibine biraz daha yaklaştırıyor!"],
	"goal_late_lead":["Gol! {name}, son bölümde takımını öne geçiriyor!","{name} atıyor! Son bölümde üstünlük el değiştiriyor!","Gol! {name}, bitime doğru çok önemli bir gol!","Top ağlarda! {name} ile son bölümde öne geçiyorlar!"],
	"goal_late_level":["Gol! {name}, son bölümde eşitlik!","{name} atıyor! Bitime doğru skor yeniden eşit!","Gol! {name}, son bölümde maça denge geliyor!","Top ağlarda! {name}, son bölümde beraberliği getiriyor!"],
	"own_goal":["Kendi kalesine! Talihsiz bir an.","Kendi kalesine gol! {name} için zor bir an.","Top kendi ağlarına gidiyor!","{name}, topu kendi kalesine gönderdi.","Talihsiz bir dokunuş, kendi kalesine gol."],
	"shot":["Vurdu!","Kaleyi deniyor!","Şut geliyor!","{name}, vuruşunu yaptı!","Kaleye bir şut!"],
	"shot_high":["Top üstten auta gitti.","Vuruşta yükseklik fazla.","Çerçevenin üzerinden dışarıda.","Kaleyi tutturamadı, top üstte kaldı.","Top yükseldi, aut.","Bu vuruş üstten dışarıya gidiyor."],
	"shot_wide":["Top yandan dışarıda.","Top direğin yanından auta çıktı.","Kaleyi bulamadı.","Vuruş çerçevenin dışında.","İsabet gelmedi, aut.","Bu denemede top yandan auta gidiyor."],
	"save":["Kaleci yerinde.","{name} kurtarıyor.","Kaleci gole izin vermedi.","Vuruşu kaleci karşıladı.","{name}, topun yolunu kesti.","Kaleci bu kez geçit vermiyor.","Kurtarış geliyor.","{name} araya giriyor."],
	"great_save":["Müthiş bir kurtarış!","{name} harika uzandı!","Kaleciden çok iyi bir müdahale!","{name}, önemli bir top çıkardı!","Kaleci gole engel oluyor!","Çok iyi uzandı, kurtarış!"],
	"woodwork":["Direk!","Top direkten döndü!","Direğe takıldı!","Direk gole izin vermiyor!","Top direğe çarptı!"],
	"corner":["Korner.","Köşe vuruşu kazanıldı.","Top kornere çıktı.","Şimdi bir köşe vuruşu.","Hücum kornerle devam edecek.","Kornerden yeniden gelecekler."],
	"free_kick":["Serbest vuruş.","Hakem düdüğü çaldı, serbest vuruş.","Oyun durdu, serbest vuruş kullanılacak.","Duran top fırsatı.","Hakem serbest vuruşu gösterdi.","Topun başına geçiyorlar, serbest vuruş."],
	"penalty":["Penaltı!","Hakem beyaz noktayı gösteriyor!","Penaltı kararı!","Düdük geldi, karar penaltı!","Beyaz noktadan kullanılacak!"],
	"offside":["Ofsayt bayrağı kalkıyor.","Ofsayt.","Bayrak havada, ofsayt var.","Hücum ofsaytla kesildi.","Yardımcı hakem ofsaytı işaret ediyor."],
	"yellow":["Sarı kart. {name} uyarıldı.","Hakem sarı kartını çıkarıyor.","{name} sarı kart görüyor.","Bu müdahaleye sarı kart.","Sarı kart çıktı, artık daha dikkatli olmalı."],
	"red":["Kırmızı kart! {name} oyundan atılıyor!","Oyundan atılma! Takım eksik kalıyor.","{name} için kırmızı kart!","Hakem kırmızı kartını gösterdi!","Kırmızı kart çıktı, maç onun için bitti!"],
	"handball":["Elle oynama!","Topa elle müdahale, düdük geliyor.","Hakem elle oynamayı gördü.","El teması var, oyun duruyor.","Düdük, elle oynama kararı."],
	"injury":["{name} için sakatlık işareti var.","{name} zorlanıyor, devam edebilecek mi?","{name} rahat hareket edemiyor.","Sakatlık var gibi, {name} sıkıntı yaşıyor.","{name} için sağlık durumuna bakılacak."],
	"halftime":["İlk yarı sona erdi.","Hakem ilk yarıyı bitiriyor.","Devre arası düdüğü geldi.","İlk yarının son düdüğü.","Takımlar soyunma odasına gidiyor."],
	"fulltime":["Son düdük! Maç sona erdi.","Ve maç bitti!","Hakemin son düdüğü geldi.","Karşılaşmanın son düdüğü geldi.","Maç tamamlandı, son düdük çaldı."],
	"substitution":["Oyuncu değişikliği.","Kenardan bir değişiklik geliyor.","Yeni bir oyuncu oyuna dahil oluyor.","Takımda oyuncu değişikliği var.","Yedek kulübesinden bir hamle."],
	"substitution_named":["{out} çıkıyor, {incoming} oyuna giriyor.","Değişiklik: {out} yerine {incoming}.","{incoming} sahaya geliyor, {out} kenara alınıyor.","{out} kenara geliyor, {incoming} artık oyunda."],
	"long_shot":["Uzaktan deniyor!","Şut, uzak mesafeden!","Mesafeye bakmadan vurdu!","{name}, uzaktan şansını deniyor!","Uzak mesafeden bir vuruş!","Kaleyi gördü, uzaktan vurdu!"],
	"header":["Kafa vuruşu!","Kafayla vuruyor!","{name}, kafayı vurdu!","Havadan gelen topa kafa!","Kafayla kaleyi deniyor!"],
	"volley":["Gelişine vurdu!","Topu kontrol etmeden vurdu!","{name}, gelişine deniyor!","Bekletmeden kaleye vurdu!","Gelişine bir vuruş!"],
	"cross":["Orta geliyor!","Top ceza sahasına gönderildi.","Ceza sahasına bir orta!","{name}, ortasını yaptı.","Ortayı gönderiyor."],
	"skill":["Şık bir hareket!","{name}, çalımı deniyor.","Topla güzel bir hareket.","{name}, ayaklarına hakim.","Rakibini hareketlendirmeye çalışıyor.","Bileklerini kullanıyor."],
	"counter":["{team}, hızlı çıkıyor!","Topu kazandılar, hızla ileri gidiyorlar.","{team}, geçiş hücumunda.","Şimdi çabuk hücum fırsatı.","Topu çabuk ileri taşıyorlar."],
	"wing_attack":["{team}, kanattan ilerliyor.","Hücumu çizgiye taşıdılar.","Kanatta topu tutup fırsat arıyorlar.","{team}, bu kez kenardan geliyor.","Oyun kanada açıldı."],
	"pressure":["{team}, rakip ceza sahasına yaklaştı.","Hücumda destek var, baskıyı sürdürüyorlar.","Ceza sahası çevresinde çoğaldılar.","{team}, hücumu kalabalık tutuyor.","Savunmanın önünde seçenek arıyorlar."],
	"build_up":["{team}, topu kaybetmeden oyun kuruyor.","Topu tutuyorlar, hücum için alan arıyorlar.","{team}, oyun kurmak için acele etmiyor.","Top onlarda, bir boşluk arıyorlar.","Sakin bir hazırlık var."],
	"late_chase":["{team}, son bölümde eşitlik arıyor.","{team} için süre azalıyor, bir gol gerekiyor.","Son bölümde beraberlik için geliyorlar.","Tek gol gerideler, son bölümde top onlarda."],
	"late_protect":["{team}, son bölümde skor avantajına sahip.","Son bölümde top öndeki takımda.","{team}, üstünken topu elinde tutuyor.","Önde olan taraf için bu topun değeri büyük."],
	"late_level":["Son bölümde skor eşit, her atak önemli.","Beraberlik sürüyor, son bölümdeyiz.","Skor eşit; tek gol her şeyi değiştirebilir.","Bitime yaklaşırken denge henüz bozulmadı."],
	"fatigue":["{team} tarafında yorgunluk belirginleşiyor.","{team} için taze kuvvetler değerli olabilir.","Yorgunluk artıyor, koşuları seçerek yapmak gerekecek.","{team}, kalan enerjisini iyi kullanmalı."],
	"rain":["Yağmurda top yerde daha çabuk hız kaybediyor.","Islak zeminde pasın şiddeti daha da önemli.","Yağmur sürüyor, topun yerdeki hızına dikkat etmek gerekiyor.","Bu zeminde pası kısa bırakmamak önemli."]
}
