extends RefCounted
## Fictional independent association. Player nationality is separate from it.
const VERSION:=1
const NATION:="SEFC"
const CLUBS:=[
	["COASTAL ROVERS","CST","TIDEMOUTH"], ["ATLAS ASTERIA","ATL","ASTERIA"],
	["IRONVALE FC","IVL","IRONVALE"], ["SOLARIS UNITED","SOL","SOLARIS"],
	["VERDANT ROVERS","VER","VERDANT"], ["NORTHSTAR FC","NST","NORTHHAVEN"],
	["PORT AZURE ATHLETIC","PAZ","PORT AZURE"], ["REDMESA SC","RDM","REDMESA"],
	["VALDORA FC","VAL","VALDORA"], ["AC MONTELAGO","MTL","MONTELAGO"],
	["BELLE RIVE FC","BRV","BELLE RIVE"], ["SV EISENBURG","EIS","EISENBURG"],
	["SANTA LUZ SC","SLZ","SANTA LUZ"], ["KASUMI CITY","KSM","KASUMI"],
	["RIO CLARO FC","RCL","RIO CLARO"], ["WESTBRIDGE UNITED","WBR","WESTBRIDGE"],
	["NOVAGRAD SC","NOV","NOVAGRAD"], ["AL NOOR FC","ANR","AL NOOR"],
	["CEDARPORT RANGERS","CDR","CEDARPORT"], ["CD ALTAVISTA","ALT","ALTAVISTA"],
	["SV ROSENFELD","RSF","ROSENFELD"], ["AC LAGO VERDE","LGV","LAGO VERDE"],
	["EASTMERE ATHLETIC","EST","EASTMERE"], ["MONTCLAIR FC","MTC","MONTCLAIR"],
	["MARAVELA CF","MAR","MARAVELA"], ["HIGHMOOR ROVERS","HMR","HIGHMOOR"],
	["SAKURAHAMA FC","SKH","SAKURAHAMA"], ["SILVERCOVE UNITED","SCV","SILVERCOVE"],
	["DUNHAVEN AFC","DUN","DUNHAVEN"], ["BELMONTE CALCIO","BLM","BELMONTE"],
	["AMBERFALL CITY","AMB","AMBERFALL"], ["PUERTO SOL FC","PSL","PUERTO SOL"],
	["VESPERA SC","VSP","VESPERA"], ["BLUEWATER TOWN","BLW","BLUEWATER"],
	["MAPLECREST FC","MPC","MAPLECREST"], ["AURELIA SPORT","AUR","AURELIA"]]
const POOLS:={
	"TR":["ARDA,EMRE,KAAN,DENİZ,MERT,BORA,EREN,ALP,KEREM,BARAN,CAN,UMUT,EFE,OZAN,TUNA,YİĞİT","AKSOY,DEMİR,KAYA,YILMAZ,ŞEN,ARSLAN,AYDIN,KILIÇ,ÇELİK,ÖZTÜRK,GÜNEŞ,YALÇIN,KARACA,TEKİN,DOĞAN,TUNÇ"],
	"ES":["DIEGO,ÁLVARO,MATEO,PABLO,ADRIÁN,IVÁN,MARCOS,SERGIO,DANIEL,JAVIER,IKER,MIGUEL,HÉCTOR,JORGE,MARIO,ANDRÉS","MORENO,ROMERO,SERRANO,VEGA,NAVARRO,TORRES,ORTEGA,RAMOS,DELGADO,CASTRO,PRIETO,MOLINA,REYES,CORTÉS,SOLER,MENDOZA"],
	"PT":["RAFAEL,TIAGO,DUARTE,JOÃO,DIOGO,AFONSO,GONÇALO,NUNO,PEDRO,MIGUEL,RUI,BRUNO,HUGO,ANDRÉ,TOMÁS,DINIS","COSTA,FERREIRA,NUNES,PINTO,LOPES,SOUSA,RIBEIRO,CARVALHO,GOMES,MENDES,RODRIGUES,TEIXEIRA,DUARTE,COELHO,BARROS,FONSECA"],
	"IT":["LUCA,MARCO,ANDREA,LORENZO,MATTEO,ALESSIO,FEDERICO,DAVIDE,SIMONE,STEFANO,GABRIELE,NICOLÒ,PAOLO,ANTONIO,GIULIO,ENRICO","ROSSI,CONTI,MORETTI,RINALDI,RICCI,MARINO,GRECO,GALLO,COSTA,FONTANA,BELLINI,LOMBARDI,FERRARA,DE LUCA,GIORDANO,VENTURI"],
	"DE":["LUKAS,LEON,FELIX,JONAS,NIKLAS,MAX,PAUL,TIM,FLORIAN,JULIAN,TOBIAS,PHILIPP,MORITZ,FABIAN,ERIK,SIMON","WEBER,FISCHER,KELLER,BRAUN,BECKER,WAGNER,HOFFMANN,KOCH,BAUER,RICHTER,WOLF,NEUMANN,SCHWARZ,KRÜGER,HARTMANN,VOGEL"],
	"FR":["HUGO,LOUIS,JULES,THÉO,GABIN,LUCAS,NOÉ,AXEL,ANTOINE,MAXIME,BASTIEN,CLÉMENT,ADRIEN,ROMAIN,ÉMILE,VALENTIN","MARTIN,MOREAU,GARNIER,DUBOIS,LAURENT,LEFÈVRE,BERNARD,ROUSSEAU,PETIT,GIRARD,FAURE,ROUX,VINCENT,FOURNIER,BLANC,MOREL"],
	"GB":["OLIVER,JACK,HARRY,THEO,ETHAN,LIAM,FINN,CHARLIE,OSCAR,JAMES,BEN,OWEN,ISAAC,LEWIS,GEORGE,TOBY","WALKER,CLARKE,BROWN,HARRIS,TURNER,HALL,COOPER,BENNETT,MORGAN,REED,BAILEY,WARD,WOOD,COLE,FOSTER,GRAY"],
	"NL":["DAAN,LUUK,FINN,SEM,BRAM,THIJS,JESSE,MEES,SIEM,STIJN,JOEP,NIELS,LARS,KOEN,WOUT,FLORIS","DE VRIES,VAN DIJK,BAKKER,VISSER,SMIT,DE BOER,MULDER,DE GROOT,BOS,VOS,DE JONG,PETERS,HENDRIKS,VAN LEEUWEN,DE WIT,VAN DEN BERG"],
	"BR":["CAIO,PEDRO,GABRIEL,MATHEUS,RAFAEL,LUCAS,BRUNO,THIAGO,VINÍCIUS,JOÃO,FELIPE,RENAN,IGOR,LEANDRO,DANILO,DAVI","SILVA,SANTOS,ALMEIDA,ROCHA,OLIVEIRA,PEREIRA,LIMA,ARAUJO,RIBEIRO,CARVALHO,FREITAS,MOREIRA,TEIXEIRA,BARBOSA,MONTEIRO,BATISTA"],
	"AR":["ENZO,JULIÁN,TOMÁS,NICOLÁS,MATEO,AGUSTÍN,FACUNDO,SANTIAGO,NAHUEL,FRANCO,LUCAS,LAUTARO,VALENTÍN,IGNACIO,RAMIRO,BRUNO","MOLINA,FERNÁNDEZ,ACOSTA,MEDINA,SUÁREZ,ROMERO,DÍAZ,ÁLVAREZ,BENÍTEZ,PEREYRA,CABRERA,ROJAS,SOSA,CASTRO,ORTIZ,IBARRA"],
	"HR":["LUKA,IVAN,MARKO,ANTE,MATEO,STIPE,NIKOLA,MARIN,JOSIP,DOMAGOJ,LOVRO,TONI,PETAR,BRUNO,FRAN,KARLO","KOVAČ,BABIĆ,HORVAT,JURIĆ,MARIĆ,NOVAK,PERIĆ,BOŽIĆ,VUKOVIĆ,KNEŽEVIĆ,BARIŠIĆ,PAVIĆ,GRGIĆ,RADIĆ,TOMIĆ,KATIĆ"],
	"NG":["CHIDI,EMEKA,FEMI,TUNDE,CHINEDU,OBINNA,CHUKWU,SEGUN,DAYO,ADEWALE,KELECHI,IFEANYI,UCHE,OLUWA,EBUKA,NNAMDI","OKORO,ADEYEMI,NWOSU,BALOGUN,OKAFOR,EZE,OBI,OKONKWO,ADEBAYO,LAWAL,BELLO,OKEKE,ONYEKA,AKINOLA,IDOWU,OGUNLEYE"],
	"JP":["REN,HARUTO,YUTO,SOTA,KAITO,TAKUMI,RYO,DAIKI,SHUN,KENTA,HIROTO,YUKI,NAOKI,AKIRA,TAICHI,KOSEI","TANAKA,SATO,NAKAMURA,ITO,SUZUKI,TAKAHASHI,WATANABE,YAMAMOTO,KOBAYASHI,KATO,YOSHIDA,YAMADA,SASAKI,YAMAGUCHI,MATSUMOTO,INOUE"]}

static func club(index: int) -> Dictionary:
	var entry: Array=CLUBS[index]
	return {"name":entry[0],"short":entry[1],"city":entry[2],"nation":NATION,"sefc_identity_version":VERSION}

static func player(serial: int) -> Dictionary:
	var codes: Array=POOLS.keys()
	var country:=posmod(serial*7,codes.size())
	var code: String=codes[country]
	var first: PackedStringArray=POOLS[code][0].split(",")
	var last: PackedStringArray=POOLS[code][1].split(",")
	# Each block changes the surname; first-team squads contain no name repeats.
	var sequence: int=serial/codes.size()
	var name: String=first[posmod(sequence*5+country*3,first.size())]+" "+last[posmod(sequence*3+(sequence/first.size())*7+country*5,last.size())]
	return {"name":name,"nationality":code,"sefc_identity_version":VERSION}

static func upgrade(w: Dictionary) -> void:
	for i in range(CLUBS.size()):
		var id:="c%02d" % i
		if not w.clubs.has(id): continue
		var c: Dictionary=w.clubs[id]
		# Rename this legacy label without reapplying player or club identities.
		if i==1 and c.name=="ATLAS FC": c.name=CLUBS[i][0]
		if int(c.get("sefc_identity_version",0))>=VERSION: continue
		c.merge(club(i),true); c.erase("squad")
	for p in w.players.values():
		# Identify the original SEFC people by immutable ID, never their current
		# employer: a Turkish/imported signing must keep his own name and country.
		if int(p.appearance_id)>=0 and int(p.appearance_id)<864 and int(p.get("sefc_identity_version",0))<VERSION:
			p.merge(player(int(p.appearance_id)),true)
	if w.get("cups",{}).get("domestic",{}).get("title","")=="SEFC ÜLKE KUPASI":
		w.cups.domestic.title="SEFC LİG KUPASI"
