#!/usr/bin/env python3
"""Build the bundled synthetic Turkish commentary; the game never uses the network.

Requires Python 3.9+, edge-tts==7.2.8 and ffmpeg. Only the authored generic
sentences in commentary_script.json are sent to the speech service.
Existing clips are reused only when their source fingerprint matches.
"""
import argparse
import asyncio
import hashlib
import json
import pathlib
import subprocess
import tempfile

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "assets/audio/commentary"
VOICES = {"spiker": "tr-TR-AhmetNeural", "yorumcu": "tr-TR-EmelNeural"}
EXCITED = {"goal", "goal_level", "goal_lead", "goal_extend", "goal_reply",
           "goal_late_lead", "goal_late_level", "great_save", "woodwork", "penalty"}
FILTER = ("silenceremove=start_periods=1:start_duration=0.015:start_threshold=-48dB,"
          "areverse,silenceremove=start_periods=1:start_duration=0.04:start_threshold=-48dB,"
          "areverse,highpass=f=85,loudnorm=I=-18:TP=-2:LRA=7,"
          "afade=t=in:d=0.008,areverse,afade=t=in:d=0.025,areverse,apad=pad_dur=0.08")


async def main():
    import edge_tts
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--jobs", type=int, default=3)
    args = parser.parse_args()
    script = json.loads((ROOT / "tools/commentary_script.json").read_text())
    OUTPUT.mkdir(parents=True, exist_ok=True)
    manifest_path = OUTPUT / "manifest.json"
    previous = json.loads(manifest_path.read_text()) if manifest_path.exists() else {}
    manifest = {"source": "Synthetic speech via Microsoft Edge TTS / edge-tts 7.2.8",
                "voices": VOICES, "clips": {}}
    cues, jobs = {}, []
    for event, pairs in script.items():
        cues[event] = []
        for index, (text, reply) in enumerate(pairs):
            cue = {"text": text, "clip": "", "reply": reply, "reply_clip": ""}
            for role, phrase, field in [("spiker", text, "clip"), ("yorumcu", reply, "reply_clip")]:
                if not phrase:
                    continue
                name = f"{event}_{index + 1:02d}_{role}.wav"
                rate = "+12%" if role == "spiker" and event in EXCITED else ("+6%" if role == "spiker" else "-3%")
                spec = {"text": phrase, "voice": VOICES[role], "rate": rate, "filter": FILTER}
                spec["fingerprint"] = hashlib.sha256(json.dumps(spec, ensure_ascii=False, sort_keys=True).encode()).hexdigest()
                manifest["clips"][name] = spec
                cue[field] = "res://assets/audio/commentary/" + name
                if not (OUTPUT / name).exists() or previous.get("clips", {}).get(name, {}).get("fingerprint") != spec["fingerprint"]:
                    jobs.append((name, spec))
            cues[event].append(cue)
    semaphore = asyncio.Semaphore(max(1, min(args.jobs, 4)))
    completed = 0

    async def render(name, spec):
        nonlocal completed
        async with semaphore:
            with tempfile.TemporaryDirectory(prefix="sefc-voice-") as temporary:
                raw = pathlib.Path(temporary) / "raw.mp3"
                for attempt in range(3):
                    try:
                        await edge_tts.Communicate(spec["text"], spec["voice"], rate=spec["rate"]).save(str(raw))
                        break
                    except Exception:
                        if attempt == 2:
                            raise
                        await asyncio.sleep(2 * (attempt + 1))
                target = pathlib.Path(temporary) / name
                await asyncio.to_thread(subprocess.run, ["ffmpeg", "-hide_banner", "-loglevel", "error", "-y",
                    "-i", str(raw), "-af", FILTER, "-ar", "24000", "-ac", "1", "-c:a", "pcm_s16le", str(target)], check=True)
                (OUTPUT / name).write_bytes(target.read_bytes())
                # Keep successful work resumable if a later network request fails.
                previous.setdefault("clips", {})[name] = spec
                manifest_path.write_text(json.dumps(previous, ensure_ascii=False, indent=2) + "\n")
            completed += 1
            if completed % 10 == 0 or completed == len(jobs):
                print(f"Rendered {completed}/{len(jobs)} clips", flush=True)

    await asyncio.gather(*(render(*job) for job in jobs))
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n")
    bank = ROOT / "scripts/commentary_voice_bank.gd"
    bank.write_text('extends RefCounted\n## Generated by tools/build_commentary_audio.py; synthetic Turkish voices.\nconst CUES := '
                    + json.dumps(cues, ensure_ascii=False, indent="\t") + '\n')
    print(f"Ready: {len(cues)} event groups, {len(manifest['clips'])} clips", flush=True)


if __name__ == "__main__":
    asyncio.run(main())
